apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logging
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      name: beats
    - port: 5000
      name: tcp
    - port: 9600
      name: monitoring
