apiVersion: v1
kind: Service
metadata:
  name: gateway-nginx
  namespace: api-gateway
spec:
  selector:
    app: gateway-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer