[package]
name = "api-gateway"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
jsonwebtoken = "8.0"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
httptest = "0.15"